// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Persistence.Main;

#nullable disable

namespace SmsTraffic.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260207145429_Init-01")]
    partial class Init01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ClientMessageBody", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClientMessageHeaderId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<string>("SmsId")
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR2(60)");

                    b.HasKey("Id");

                    b.HasIndex("ClientMessageHeaderId");

                    b.HasIndex("Phone");

                    b.HasIndex("SmsId");

                    b.ToTable("ClientMessageBody", null, t =>
                        {
                            t.HasComment("Сообщения клиентов дочерняя часть");
                        });
                });

            modelBuilder.Entity("Domain.Entities.ClientMessageHeader", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("Code")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DateSentToProvider")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("RemoteIp")
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<string>("Response")
                        .HasColumnType("CLOB");

                    b.Property<int?>("Result")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("DateCreation");

                    b.HasIndex("DateSentToProvider");

                    b.ToTable("ClientMessageHeader", null, t =>
                        {
                            t.HasComment("Сообщения клиентов главная часть");
                        });
                });

            modelBuilder.Entity("Domain.Entities.ClientMessageBody", b =>
                {
                    b.HasOne("Domain.Entities.ClientMessageHeader", "ClientMessageHeader")
                        .WithMany("ClientMessageBodies")
                        .HasForeignKey("ClientMessageHeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClientMessageHeader");
                });

            modelBuilder.Entity("Domain.Entities.ClientMessageHeader", b =>
                {
                    b.Navigation("ClientMessageBodies");
                });
#pragma warning restore 612, 618
        }
    }
}
