// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Persistence.Main;

#nullable disable

namespace SmsTraffic.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ClientMessageBody", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_MESSAGE_BODY");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClientMessageHeaderId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_MESSAGE_HEADER");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("PHONE");

                    b.Property<string>("SmsId")
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR2(60)")
                        .HasColumnName("SMS_ID");

                    b.HasKey("Id");

                    b.HasIndex("ClientMessageHeaderId");

                    b.HasIndex("Phone");

                    b.HasIndex("SmsId");

                    b.ToTable("ClientMessageBody", null, t =>
                        {
                            t.HasComment("Сообщения клиентов дочерняя часть");
                        });
                });

            modelBuilder.Entity("Domain.Entities.ClientMessageHeader", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_MESSAGE_HEADER");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATE_CREATION");

                    b.Property<DateTime?>("DateSentToProvider")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATE_SENT_TO_PROVIDER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("MESSAGE");

                    b.Property<string>("RemoteIp")
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("REMOTE_IP");

                    b.Property<string>("Response")
                        .HasColumnType("CLOB")
                        .HasColumnName("RESPONSE");

                    b.Property<int?>("ResponseCode")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("RESPONSE_CODE");

                    b.Property<string>("ResponseDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("RESPONSE_DESCRIPTION");

                    b.Property<int?>("ResponseResult")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("RESPONSE_RESULT");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.HasIndex("DateCreation");

                    b.HasIndex("DateSentToProvider");

                    b.HasIndex("RemoteIp");

                    b.ToTable("ClientMessageHeader", null, t =>
                        {
                            t.HasComment("Сообщения клиентов главная часть");
                        });
                });

            modelBuilder.Entity("Domain.Entities.ClientMessageBody", b =>
                {
                    b.HasOne("Domain.Entities.ClientMessageHeader", "ClientMessageHeader")
                        .WithMany("ClientMessageBodies")
                        .HasForeignKey("ClientMessageHeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClientMessageHeader");
                });

            modelBuilder.Entity("Domain.Entities.ClientMessageHeader", b =>
                {
                    b.Navigation("ClientMessageBodies");
                });
#pragma warning restore 612, 618
        }
    }
}
